version: "3.8"
services:
  mysqldb:
    image: "mysql:latest"
    container_name: mysqldb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: calculator
      MYSQL_USER: calculator
      MYSQL_PASSWORD: calculator
      MYSQL_ROOT_PASSWORD: calculator